### ISSUE TITLE
scope not working 'correctly'

### ISSUE THREAD

**Issue by guarin1949** [mathspp/building-a-python-compiler-and-interpreter#1]
I get the following error when I run 'python -m pytcomp.interpreter "a = b + 3":

(pytcomp) PS E:\Projects\pytcomp> python -m pytcomp.interpreter "a = b + 3"
bc: Bytecode(BytecodeType.LOAD, 'b')
bc.value: b
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Projects\pytcomp\src\pytcomp\interpreter.py", line 105, in <module>
    Interpreter(bytecode).interpret()
  File "E:\Projects\pytcomp\src\pytcomp\interpreter.py", line 50, in interpret
    interpret_method(bc)
  File "E:\Projects\pytcomp\src\pytcomp\interpreter.py", line 88, in interpret_load
    self.stack.push(self.scope[bc.value])
                    ~~~~~~~~~~^^^^^^^^^^
KeyError: 'b'

I have looked through the code for 0.6.0, 0.7.0, 0.8.0, and 0.9.0 and have not found anywhere that 'b' (or anything) is added to scope.
HELP! :)
This error occurs when I run your code as well:

(pytcomp) PS E:\Projects\pytcomp\0.6.0\src> python -m python.interpreter "a = b + 3"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Projects\pytcomp\0.6.0\src\python\interpreter.py", line 101, in <module>
    Interpreter(bytecode).interpret()
  File "E:\Projects\pytcomp\0.6.0\src\python\interpreter.py", line 48, in interpret
    interpret_method(bc)
  File "E:\Projects\pytcomp\0.6.0\src\python\interpreter.py", line 84, in interpret_load
    self.stack.push(self.scope[bc.value])
                    ~~~~~~~~~~^^^^^^^^^^
KeyError: 'b'

I am running python 3.12.1 on Windows 11 in a virtual environment.

I am really enjoying this series; brings back pleasant memories of a compiler construction class from grad school a gazillion years ago...

**Comment by rodrigogiraoserrao** [comment]
Hey, I'm a bit confused. What did you expect to happen when you run `a = b + 3`..?
If I open a Python REPL and type `a = b + 3` I also get an error because `b` is undefined.

---

I'm glad you're enjoying the series :)

**Comment by guarin1949** [comment]
Oops, now I feel like an idiot...(;>}).
Thanks for responding.  Chapter 6 works fine now.  Still struggling with
7.  I particularly liked the visitor pattern...
Are you interested in typos?
Thanx,
Warren

**Comment by rodrigogiraoserrao** [comment]
No worries, and thanks for your kind words!
I'll close this issue because the original issue has been solved.

Feel free to send typos my way, yes. You can email me the typos or open an issue on my blog repo: https://github.com/mathspp/mathspp.
